version: "3.8"

services:
  login-app:
    environment:
      - DEBUG=*
      - NODE_ENV=development
      - MONGODB_URI=mongodb://localhost:27017/logindb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=login-app"
    volumes:
      - ./logs:/usr/src/app/logs
      - /var/log/mongodb:/var/log/mongodb:ro
