services:
  login-app:
    image: ${ECR_REGISTRY}/login-ejemplo:latest
    ports:
      - "80:3000" # Map app port 3000 in the container to port 80 on the host
      # - "27017:27017" # Uncomment only if you need to access MongoDB from your host (not needed for normal app use)
    volumes:
      - mongodb_data:/data/db
      - ./logs:/var/log/mongodb
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    init: true # Helps with process management inside container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s # Increased interval to reduce load
      timeout: 15s # Increased timeout
      retries: 5 # More retries
      start_period: 90s # More time for startup

volumes:
  mongodb_data:
    driver: local
