version: "3.8"

services:
  login-app:
    # Try private ECR first, fallback to public ECR if auth fails
    image: ${ECR_REGISTRY:-public.ecr.aws/diego-public}/login-ejemplo:${IMAGE_TAG:-latest}
    ports:
      - "${HOST_PORT:-80}:3000"
    volumes:
      - ./logs:/var/log/app
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGO_URI=mongodb://mongodb:27017/login-database
      - MONGODB_URI=mongodb://mongodb:27017/login-database
    restart: unless-stopped
    init: true
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 90s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./logs:/var/log/mongodb
    environment:
      - MONGO_INITDB_DATABASE=login-database
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
