name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Docker Hub (puedes cambiar por ECR si lo necesitas)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Instala dependencias y corre pruebas Jest
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with Jest
        run: npm test

      # Build and push images (Docker Bake si existe, Compose si no)
      - name: Build and push Docker images (Bake or Compose)
        run: |
          if [ -f docker-bake.hcl ]; then
            docker buildx bake --push
          else
            docker compose build
            docker compose push
          fi

      # Despliegue remoto en EC2 vía SSH (solo pull y up, sin git pull)
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/LoginDeploy
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker compose pull
            docker compose up -d --remove-orphans
